# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurUsers',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
