# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourusers',
            name='username',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
