# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_ourusers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.EmailField(max_length=50)),
                ('request_to', models.EmailField(max_length=50)),
            ],
        ),
    ]
