# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0006_auto_20180123_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_requests',
            name='request_from',
            field=models.EmailField(max_length=50),
        ),
    ]
