# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0007_auto_20180123_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_requests',
            name='request_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_signup.OurUsers'),
        ),
    ]
