# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourusers',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
