# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0010_auto_20180128_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(auto_created=True, null=True)),
                ('post', models.TextField(max_length=1000)),
                ('post_time', models.DateTimeField()),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login_signup.OurUsers')),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('posted_by', 'post_time')]),
        ),
    ]
