# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0012_auto_20180130_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.TextField(max_length=1000)),
                ('comment_time', models.DateTimeField()),
                ('comment_by', models.EmailField(max_length=254)),
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(auto_created=True, default=20, primary_key=True, serialize=False),
        ),
    ]
